"""Application service layer."""
from alpha.services.projects import (
    autosave_project_settings,
    create_project,
    get_project,
    rename_project,
    reopen_project,
)
from alpha.services.script_projection import (
    compute_projection_payload,
    create_script_version,
    get_active_scenes,
    get_current_script_projection,
    get_current_script_text,
    get_scene,
    get_script_version,
    initialize_scenes_from_script,
    remove_scene_from_active_order,
    reorder_scenes,
    restore_scene_narration,
    update_scene_narration,
    update_scene_visuals,
)
from alpha.services.artifacts import (
    create_artifact_version,
    get_artifact_slot,
    get_artifact_version,
    get_or_create_artifact_slot,
    record_generation_attempt,
    select_artifact_version,
    set_slot_compatibility,
    set_slot_review_needed,
)

__all__ = [
    "create_project",
    "get_project",
    "rename_project",
    "reopen_project",
    "autosave_project_settings",
    "create_script_version",
    "initialize_scenes_from_script",
    "update_scene_narration",
    "update_scene_visuals",
    "reorder_scenes",
    "remove_scene_from_active_order",
    "restore_scene_narration",
    "get_active_scenes",
    "get_scene",
    "get_current_script_projection",
    "get_script_version",
    "get_current_script_text",
    "compute_projection_payload",
    "create_artifact_version",
    "get_or_create_artifact_slot",
    "select_artifact_version",
    "record_generation_attempt",
    "set_slot_compatibility",
    "set_slot_review_needed",
    "get_artifact_slot",
    "get_artifact_version",
]

