# Generated by Django 5.2.17 on 2026-10-06 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DurabilityJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128, unique=True)),
                ('rev', models.PositiveIntegerField(default=0)),
                ('state', models.CharField(default='active', max_length=64)),
                ('payload', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'alpha_durability_journal',
                'constraints': [models.CheckConstraint(condition=models.Q(('rev__gte', 0)), name='durability_journal_rev_non_negative')],
            },
        ),
        migrations.CreateModel(
            name='DurabilityChild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='alpha.durabilityjournal')),
            ],
            options={
                'db_table': 'alpha_durability_child',
                'constraints': [models.UniqueConstraint(fields=('journal', 'name'), name='durability_unique_journal_child_name')],
            },
        ),
    ]
