# Generated by Django 5.2.17 on 2026-10-06 10:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creation_token', models.CharField(db_index=True, max_length=128)),
                ('title', models.CharField(max_length=255)),
                ('rev', models.IntegerField(default=1)),
                ('lifecycle_state', models.CharField(choices=[('ACTIVE', 'Active'), ('RENDERING', 'Rendering'), ('DELETED', 'Soft Deleted'), ('PURGED', 'Purged')], default='ACTIVE', max_length=32)),
                ('input_mode', models.CharField(choices=[('TOPIC', 'Topic Prompt'), ('PASTED_SCRIPT', 'Pasted Script')], default='TOPIC', max_length=32)),
                ('target_duration_seconds', models.IntegerField(default=300)),
                ('target_language', models.CharField(default='en', max_length=16)),
                ('visual_style', models.CharField(choices=[('MINIMAL_ILLUSTRATION', 'Minimal Illustration'), ('STORYBOOK', 'Storybook'), ('DOCUMENTARY_ILLUSTRATION', 'Documentary Illustration')], default='MINIMAL_ILLUSTRATION', max_length=64)),
                ('captions_enabled', models.BooleanField(default=True)),
                ('motion_enabled', models.BooleanField(default=True)),
                ('music_enabled', models.BooleanField(default=False)),
                ('voice_id', models.CharField(blank=True, default='', max_length=64)),
                ('render_locked', models.BooleanField(default=False)),
                ('current_render_lock_id', models.CharField(blank=True, max_length=128, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('retention_deadline', models.DateTimeField(blank=True, null=True)),
                ('storage_bytes', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OriginalInput',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('input_mode', models.CharField(choices=[('TOPIC', 'Topic Prompt'), ('PASTED_SCRIPT', 'Pasted Script')], max_length=32)),
                ('raw_text', models.TextField()),
                ('input_language', models.CharField(default='en', max_length=16)),
                ('word_count', models.IntegerField()),
                ('byte_count', models.IntegerField()),
                ('content_sha256', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='original_input', to='alpha.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('user', 'creation_token'), name='unique_user_project_creation_token'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(condition=models.Q(('rev__gte', 1)), name='check_project_rev_gte_1'),
        ),
    ]
