# Generated by Django 5.2.17 on 2026-10-06 11:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha', '0002_project_originalinput_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScriptVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.IntegerField()),
                ('text', models.TextField()),
                ('source_type', models.CharField(choices=[('GENERATED', 'Generated Script'), ('EDITED', 'User Edited Script'), ('PROJECTED', 'Projected From Scenes'), ('FACTUAL_CORRECTION', 'Factual Correction'), ('RESTORED', 'Restored Script')], default='GENERATED', max_length=32)),
                ('content_sha256', models.CharField(max_length=64)),
                ('word_count', models.IntegerField()),
                ('byte_count', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='script_versions', to='alpha.project')),
            ],
            options={
                'ordering': ['project', '-version_number'],
            },
        ),
        migrations.CreateModel(
            name='ScriptProjection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField(blank=True, default='')),
                ('content_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('word_count', models.IntegerField(default=0)),
                ('byte_count', models.IntegerField(default=0)),
                ('scene_count', models.IntegerField(default=0)),
                ('active_scene_ids', models.JSONField(default=list)),
                ('scene_spans', models.JSONField(default=list)),
                ('projection_rev', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='script_projection', to='alpha.project')),
                ('source_script_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projections', to='alpha.scriptversion')),
            ],
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_index', models.IntegerField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('source_start_char', models.IntegerField(default=0)),
                ('source_end_char', models.IntegerField(default=0)),
                ('narration_text', models.TextField()),
                ('visual_description', models.TextField(blank=True, default='')),
                ('generation_prompt', models.TextField(blank=True, default='')),
                ('review_flags', models.JSONField(default=dict)),
                ('rev', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='alpha.project')),
                ('source_script_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_scenes', to='alpha.scriptversion')),
            ],
            options={
                'ordering': ['project', 'order_index'],
            },
        ),
        migrations.CreateModel(
            name='SceneNarrationVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.IntegerField()),
                ('text', models.TextField()),
                ('content_sha256', models.CharField(max_length=64)),
                ('word_count', models.IntegerField()),
                ('byte_count', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='narration_versions', to='alpha.scene')),
            ],
            options={
                'ordering': ['scene', '-version_number'],
                'constraints': [models.UniqueConstraint(fields=('scene', 'version_number'), name='unique_scene_narration_version_number'), models.CheckConstraint(condition=models.Q(('version_number__gte', 1)), name='check_scene_narration_version_gte_1')],
            },
        ),
        migrations.AddConstraint(
            model_name='scriptversion',
            constraint=models.UniqueConstraint(fields=('project', 'version_number'), name='unique_project_script_version_number'),
        ),
        migrations.AddConstraint(
            model_name='scriptversion',
            constraint=models.CheckConstraint(condition=models.Q(('version_number__gte', 1)), name='check_script_version_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='scriptprojection',
            constraint=models.CheckConstraint(condition=models.Q(('projection_rev__gte', 1)), name='check_projection_rev_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='scene',
            constraint=models.CheckConstraint(condition=models.Q(('rev__gte', 1)), name='check_scene_rev_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='scene',
            constraint=models.CheckConstraint(condition=models.Q(('source_start_char__gte', 0)), name='check_scene_start_char_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='scene',
            constraint=models.CheckConstraint(condition=models.Q(('source_end_char__gte', models.F('source_start_char'))), name='check_scene_end_gte_start'),
        ),
    ]
