# Generated by Django 5.2.17 on 2026-10-06 11:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha', '0003_scriptversion_scriptprojection_scene_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtifactSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('IMAGE', 'Image'), ('AUDIO', 'Audio'), ('TIMING', 'Timing'), ('CAPTION', 'Caption')], db_index=True, max_length=32)),
                ('slot_key', models.CharField(default='default', max_length=64)),
                ('is_compatible', models.BooleanField(default=True)),
                ('needs_review', models.BooleanField(default=False)),
                ('review_reason', models.CharField(blank=True, default='', max_length=255)),
                ('last_attempt_outcome', models.CharField(choices=[('NONE', 'No Attempt'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('UNCERTAIN', 'Uncertain')], default='NONE', max_length=32)),
                ('last_attempt_id', models.CharField(blank=True, default='', max_length=64)),
                ('last_attempt_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifact_slots', to='alpha.project')),
                ('scene', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artifact_slots', to='alpha.scene')),
            ],
            options={
                'ordering': ['project', 'scene', 'kind', 'slot_key'],
            },
        ),
        migrations.CreateModel(
            name='ArtifactAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attempt_id', models.CharField(max_length=64)),
                ('outcome', models.CharField(choices=[('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('UNCERTAIN', 'Uncertain')], max_length=32)),
                ('error_message', models.TextField(blank=True, default='')),
                ('diagnostic_data', models.JSONField(default=dict)),
                ('provider', models.CharField(blank=True, default='', max_length=64)),
                ('model', models.CharField(blank=True, default='', max_length=128)),
                ('effective_config', models.JSONField(default=dict)),
                ('pinned_source_versions', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifact_attempts', to='alpha.project')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='alpha.artifactslot')),
            ],
            options={
                'ordering': ['slot', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArtifactVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('IMAGE', 'Image'), ('AUDIO', 'Audio'), ('TIMING', 'Timing'), ('CAPTION', 'Caption')], db_index=True, max_length=32)),
                ('version_number', models.IntegerField()),
                ('source_type', models.CharField(choices=[('GENERATED', 'Generated'), ('EDITED', 'User Edited'), ('UPLOADED', 'User Uploaded'), ('RESTORED', 'Restored Version')], default='GENERATED', max_length=32)),
                ('storage_key', models.CharField(blank=True, default='', max_length=512)),
                ('byte_hash', models.CharField(blank=True, default='', max_length=64)),
                ('byte_count', models.BigIntegerField(default=0)),
                ('mime_type', models.CharField(blank=True, default='', max_length=128)),
                ('structured_payload', models.JSONField(blank=True, null=True)),
                ('payload_schema_version', models.IntegerField(default=1)),
                ('pinned_source_versions', models.JSONField(default=dict)),
                ('provider', models.CharField(blank=True, default='', max_length=64)),
                ('model', models.CharField(blank=True, default='', max_length=128)),
                ('effective_config', models.JSONField(default=dict)),
                ('effective_config_signature', models.CharField(blank=True, default='', max_length=64)),
                ('is_valid', models.BooleanField(default=True)),
                ('validation_metadata', models.JSONField(default=dict)),
                ('operation_id', models.CharField(blank=True, default='', max_length=64)),
                ('attempt_id', models.CharField(blank=True, default='', max_length=64)),
                ('generation_outcome', models.CharField(choices=[('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('UNCERTAIN', 'Uncertain')], default='SUCCEEDED', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifact_versions', to='alpha.project')),
                ('scene', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artifact_versions', to='alpha.scene')),
                ('source_narration_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_artifacts', to='alpha.scenenarrationversion')),
                ('source_script_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_artifacts', to='alpha.scriptversion')),
            ],
            options={
                'ordering': ['project', 'scene', 'kind', '-version_number'],
            },
        ),
        migrations.AddField(
            model_name='artifactslot',
            name='selected_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_in_slots', to='alpha.artifactversion'),
        ),
        migrations.AddConstraint(
            model_name='artifactversion',
            constraint=models.CheckConstraint(condition=models.Q(('version_number__gte', 1)), name='check_artifact_version_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='artifactversion',
            constraint=models.UniqueConstraint(condition=models.Q(('scene__isnull', False)), fields=('project', 'scene', 'kind', 'version_number'), name='unique_scene_artifact_version'),
        ),
        migrations.AddConstraint(
            model_name='artifactversion',
            constraint=models.UniqueConstraint(condition=models.Q(('scene__isnull', True)), fields=('project', 'kind', 'version_number'), name='unique_project_artifact_version'),
        ),
        migrations.AddConstraint(
            model_name='artifactslot',
            constraint=models.UniqueConstraint(condition=models.Q(('scene__isnull', False)), fields=('project', 'scene', 'kind', 'slot_key'), name='unique_scene_artifact_slot'),
        ),
        migrations.AddConstraint(
            model_name='artifactslot',
            constraint=models.UniqueConstraint(condition=models.Q(('scene__isnull', True)), fields=('project', 'kind', 'slot_key'), name='unique_project_artifact_slot'),
        ),
    ]
